export const objects = [
    {
      type: 'ground',
      name: 'ground',
      x: 0,
      y: 0,
      z: 0,
      rotation: {
        x: - Math.PI / 2,
        y: 0,
        z: 0,
      },
      show: true,
      width: 200,
      height: 100,
      color: 0x13e260,
      widthSegments: 10,
      heightSegments: 10,
      emissive: ''
    },
    {
      type: 'wall',
      name: 'top-wall',
      x: 0,
      y: 10,
      z: -50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 200,
      height: 20,
      depth : 4,
      color: 0xffffff,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments : 10,
    },
    {
      type: 'wall',
      name: 'bottom-wall',
      x: 0,
      y: 10,
      z: 50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 200,
      height: 20,
      depth : 4,
      color: 0xffffff,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments : 10,
    },
    {
      type: 'wall',
      name: 'left-wall',
      x: -100,
      y: 10,
      z: 0,
      rotation: {
        x: 0,
        y: Math.PI / 2,
        z: 0,
      },
      show: true,
      width: 100,
      height: 20,
      depth : 4,
      color: 0xffffff,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments : 10,
    },
    {
      type: 'wall',
      name: 'right-wall',
      x: 100,
      y: 10,
      z: 0,
      rotation: {
        x: 0,
        y: Math.PI / 2,
        z: 0,
      },
      show: true,
      width: 100,
      height: 20,
      depth : 4,
      color: 0xffffff,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments : 10,
    },
    {
      type: 'window',
      name: 'window1',
      x: 70,
      y: 10,
      z: -50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 10,
      height: 10,
      depth: 4,
      color: 0x096aa8,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
    },
    {
      type: 'window',
      name: 'window2',
      x: 30,
      y: 10,
      z: -50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 10,
      height: 10,
      depth: 4,
      color: 0x096aa8,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
    },
    {
      type: 'window',
      name: 'window3',
      x: -30,
      y: 10,
      z: -50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 10,
      height: 10,
      depth: 4,
      color: 0x096aa8,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
    },
    {
      type: 'window',
      name: 'window4',
      x: -70,
      y: 10,
      z: -50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 10,
      height: 10,
      depth: 4,
      color: 0x096aa8,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
    },
    {
      type: 'door',
      name: 'door',
      x: 0,
      y: 10,
      z: 50,
      rotation: {
        x: 0,
        y: 0,
        z: 0,
      },
      show: true,
      width: 10,
      height: 20,
      depth: 5,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
    },
    {
      type: 'shelves',
      name: 'shelves1',
      x: -50,
      y: 0,
      z: 0,
      rotation: {
        x: 0,
        y: - Math.PI / 2,
        z: 0,
      },
      show: true,
      width: 10,
      height: 20,
      depth: 2,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
      clickable: true
    },
    {
      type: 'shelves',
      name: 'shelves2',
      x: -20,
      y: 0,
      z: 0,
      rotation: {
        x: 0,
        y: - Math.PI / 2,
        z: 0,
      },
      show: true,
      width: 10,
      height: -20,
      depth: 2,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
      clickable: true
    },
    {
      type: 'shelves',
      name: 'shelves3',
      x: 20,
      y: 0,
      z: 0,
      rotation: {
        x: 0,
        y: - Math.PI / 2,
        z: 0,
      },
      show: true,
      width: 10,
      height: 20,
      depth: 2,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
      clickable: true
    },
    {
      type: 'shelves',
      name: 'shelves4',
      x: 50,
      y: 0,
      z: 0,
      rotation: {
        x: 0,
        y: - Math.PI / 2,
        z: 0,
      },
      show: true,
      width: 10,
      height: 20,
      depth: 2,
      widthSegments: 10,
      heightSegments: 10,
      depthSegments: 10,
      clickable: true
    },
  ]